### ISSUE TITLE
freezegun crashes with cryptography 1.2 because of integer dict keys

### ISSUE THREAD

**Issue by felliott** [spulec/freezegun#126]
Hello,

I originally filed this on cryptography, but they said it was probably more appropriate for freezegun or cffi.  Please let me know if you think it's more appropriate for cffi.  Thank you!

Cheers,
Fitz

Original bug report:
----

With the release of cryptography-1.2.0, my freezegun-using tests have started crashing.  The traceback looks like:

````
Traceback (most recent call last):
  File "breaker2.py", line 10, in <module>
    with freezegun.freeze_time('2015-10-31 12:00:01'):
  File "/Users/fitz/.virtualenvs/cgdb/lib/python3.4/site-packages/freezegun/api.py", line 321, in __enter__
    self.start()
  File "/Users/fitz/.virtualenvs/cgdb/lib/python3.4/site-packages/freezegun/api.py", line 374, in start
    for module_attribute in dir(module):
TypeError: unorderable types: str() < int()
````

The crash occurs on [this line](https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L375) when freezegun attempts to `dir()` on `_cffi_backend._extern_py`.  That module has integer keys in its `__dict__` method, causing the above error.  The dump of the `__dict__` looks like this:

````
{4441887152: (<ctype 'void(*)(int, int, char *, int)'>,
              <bound method type._lock_cb of <class 'cryptography.hazmat.bindings.openssl.binding.Binding'>>,
              b'\x00\x00\x00\x00\x00\x00\x00\x00',
              None),
 4441887184: (<ctype 'int(*)(char *, int, int, void *)'>,
              <function _pem_password_cb at 0x1077e3488>,
              b'\x00\x00\x00\x00\x00\x00\x00\x00',
              None),
 4441887216: (<ctype 'int(*)(unsigned char *, int)'>,
              <function _osrandom_rand_bytes at 0x108b6f2f0>,
              b'\xff\xff\xff\xff\x00\x00\x00\x00',
              None),
 4441887248: (<ctype 'int(*)()'>,
              <function _osrandom_rand_status at 0x108b6f378>,
              b'\x00\x00\x00\x00\x00\x00\x00\x00',
              None),
 '__doc__': None,
 '__loader__': None,
 '__name__': '_cffi_backend._extern_py',
 '__package__': None,
 '__spec__': None}
````

The suspect commit is 830af271de1c9c358, when cryptography was updated to use cffi's static callbacks.  [Here is a sample script that demonstrates the breakage.](https://gist.github.com/felliott/4547366a649dac4df6d1)

I'm relatively new to Python, so I'm not sure if this is a bug in cffi, cryptography, or freezegun. I'm happy to refile elsewhere if needed.  Please let me know if you need any more information.  Thank you very much and have a great day!

Cheers,
Fitz

**Comment by felliott** [comment]
Never mind, just saw the [closed issue](https://github.com/spulec/freezegun/issues/123).  Sorry for the noise!

Cheers,
Fitz

**Comment by felliott** [comment]
Oops, this is still broken.  The error is in (or is also in) [this line](https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L375) which is not in the try/catch block.  Calling `dir(module)` on `_cffi_backend._extern_py` causes the crash.   Please let me know if I can provide any other information.  Thank you!

Cheers,
Fitz

**Comment by sfontana** [comment]
Also affected by this issue

**Comment by spulec** [comment]
This seems like either a bug in cffi or `dir`, right? Is it an expected case that `dir` will raise this type of error?

**Comment by JanMalte** [comment]
+1

**Comment by Adaptification** [comment]
+1 Even if it is an upstream bug, it would be nice if freezegun worked around the bug by itself until it was fixed.

**Comment by thinkt4nk** [comment]
+1

**Comment by JanMalte** [comment]
Seems like it won't be fixed in cffi and therefor a fix must be provided by freezegun
https://bitbucket.org/cffi/cffi/issues/250/integers-as-keys-in-module

**Comment by kdeldycke** [comment]
CFFI seems to have been fixed: https://bitbucket.org/cffi/cffi/issues/250/integers-as-keys-in-module

**Comment by kdeldycke** [comment]
As a result a simple requirement of `cffi > 1.5.2` should be enough to close this issue.
