### ISSUE TITLE
CPython detection appears broken in 0.3.6

### ISSUE THREAD

**Issue by JDiPierro** [spulec/freezegun#137]
Cpython detection doesn't seem to be working in 0.3.6

    >>> import platform
    >>> import freezegun
    >>> freezegun.api._is_cpython
    False
    >>> hasattr(platform, 'python_implementation')
    True
    >>> platform.python_implementation().lower() == "cpython"
    True
    >>> hasattr(platform, 'python_implementation') and platform.python_implementation().lower() == "cpython"
    True
    >>> (hasattr(platform, 'python_implementation') and platform.python_implementation().lower() == "cpython")
    True
    >>> platform.python_implementation()
    'CPython'
    >>> freezegun.freeze_time("2016-02-12 12:20:00PM")
    <freezegun.api._freeze_time object at 0x10ba9bb90>
    >>> freezegun.freeze_time("2016-02-12 12:20:00PM", tick=True)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/justindipierro/.virtualenvs/studio/lib/python2.7/site-packages/freezegun/api.py", line 471, in freeze_time
        raise SystemError('Calling freeze_time with tick=True is only compatible with CPython')
    SystemError: Calling freeze_time with tick=True is only compatible with CPython

Freezegun Version:

    $ pip freeze | grep freeze
    freezegun==0.3.6

**Comment by spulec** [comment]
Yes, this is fixed in master with https://github.com/spulec/freezegun/pull/135. I'll hopefully be able to get a new release out soon.

**Comment by nebulans** [comment]
New release would be really useful for me

**Comment by JDiPierro** [comment]
@nebulans FYI in case you don't know: You can specify a specific commit in your `requirements.pip` file. We've got this for `freezegun` right now:

    -e git+git@github.com:spulec/freezegun.git@e79c0fbf1cbd722201f7997b20559f79f3810d3b#egg=freezegun

Though a new release would really make sense considering the severity of this bug...

**Comment by spulec** [comment]
`0.3.7` is now available.
