### ISSUE TITLE
Please Publish 0.3.7 As Soon As Possible

### ISSUE THREAD

**Issue by Miserlou** [spulec/freezegun#141]
Because of Issue #137 , the currently published version of freezegun is significantly broken!

This ticket is to remind you to please publish a fixed version! The fix is already commited, it simply needs to be published!

In the meantime, other weary travelers can use this to solve their tick woes:

    pip uninstall freezegun
    pip install -e git+git@github.com:spulec/freezegun.git@e79c0fbf1cbd722201f7997b20559f79f3810d3b#egg=freezegun

**Comment by spulec** [comment]
`0.3.7` is now available
