### ISSUE TITLE
Scale ticks to simulate hours/days passing automatically

### ISSUE THREAD

**Issue by thedrow** [spulec/freezegun#142]
I got that idea from [timecop](https://github.com/travisjeffery/timecop#timecopscale).
Basically it means that every tick will "travel" a predefined amount of time instead of just one second.
It's currently possible to do that manually but it'd be nice to be able to do so automatically as well.

**Comment by spulec** [comment]
Agreed, would be happy to accept a PR.

**Comment by sheepsy90** [comment]
Added pull request

**Comment by spulec** [comment]
Closed with #201
