### ISSUE TITLE
Ignore doesn't work for time since it doesn't patch the whole module

### ISSUE THREAD

**Issue by jurriaan** [spulec/freezegun#143]
It rather patches only a few methods which results in all modules being patched. 
Also those that are specified in the ignore list.

How to fix this: instead of patching separate methods, the whole module should be replaced so that ignored modules can access the proper time methods.

**Comment by spulec** [comment]
Just to make sure I understand, you want to patch the `datetime` module, but not the `time` module?

**Comment by jurriaan** [comment]
I wanted the ignore option to work for classes that use the `time` module, so that these modules can call the original `time.time` method. This currently doesn't work, because it's not the `time` module that's patched, but rather the individual methods of this module. That means that, since the time module is shared among all modules using it, it's also being patched for modules specified in the ignore option of `freeze_time`.

**Comment by jurriaan** [comment]
The ignore option should make sure the specified modules can access the original time/datetime methods. Currently it only works for datetime.

I wanted the ignore option to work for modules that use the `time` module, so that these modules can call the original `time.time` method. This currently doesn't work, because it's not the `time` module that's patched, but rather the individual methods of this module. That means that, since the time module is shared among all modules using it, it's also being patched for modules specified in the ignore option of `freeze_time`.

**Comment by spulec** [comment]
I don't see a way to do this. Feel free to reopen with some ideas.
