### ISSUE TITLE
`FrozenDateTimeFactory` missing `move_to` method.

### ISSUE THREAD

**Issue by tomrlu** [spulec/freezegun#146]
In the version of `freezetime` on PyPI, `FrozenDateTimeFactory` is missing `move_to` method.

```
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 19 2015, 20:38:52) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import freezegun
>>> from freezegun import freeze_time
>>> freezegun.__version__
'0.3.7'
>>> with freeze_time('Jan 1st, 2000') as frozen_datetime:
...     frozen_datetime.move_to
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: 'FrozenDateTimeFactory' object has no attribute 'move_to'
>>> 
```

EDIT: grabbed the tarball from PyPI; `move_to` isn't in `freezegun/api.py` 🙂
```python
# freezegun/api.py
. . .
class FrozenDateTimeFactory(object):

    def __init__(self, time_to_freeze):
        self.time_to_freeze = time_to_freeze

    def __call__(self):
        return self.time_to_freeze

    def tick(self, delta=datetime.timedelta(seconds=1)):
        self.time_to_freeze += delta
. . .
```

**Comment by spulec** [comment]
I can't seem to find this method in the python documentation (https://docs.python.org/2/library/datetime.html).

**Comment by tomrlu** [comment]
It's in the freezegun readme
https://github.com/spulec/freezegun#moving-time-to-specify-datetime

It's also in the source on GitHub, actually.
https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L280

**Comment by spulec** [comment]
Oh, my bad. I just haven't pushed out a new release yet. Feel free to install from Github and I should be getting a new release out soon.

**Comment by tomrlu** [comment]
Ah, alright. Thanks for the help!

**Comment by ezarowny** [comment]
Bumping this. Can you push a release to PyPI?

**Comment by spulec** [comment]
Version 0.3.8 is now released
