### ISSUE TITLE
please update version number for new api with .move_to

### ISSUE THREAD

**Issue by stefanocrosta** [spulec/freezegun#158]
current version in pypi is 0.3.7; current version in repo is 0.3.7

But they are very different - pypi version is missing `.move_to()` ! Took me quite a while to understand what was going on ;-)

I can do a pull request but just for changing the setup.py feels a bit too much. Also this description might help somebody else running into the same!

It also would be good to add in the docs some good practices on how to use it when not using a context_manager; i'm doing:

```
freezer = freeze_time("2012-01-14 12:00:01")
frozen = freezer.start()
assert datetime.datetime.now() == datetime.datetime(2012, 1, 14, 12, 0, 1)
frozen.move_to("2012-01-15 12:00:01")
assert datetime.datetime.now() == datetime.datetime(2012, 1, 15, 12, 0, 1)
freezer.stop()
```

and hoping it's the "best practice" way (I cannot use the context manager because of the way the freezegun is initialized).

**Comment by spulec** [comment]
I've just released `0.3.8`.

Yes, that is the correct way to use it.
