### ISSUE TITLE
default=datetime.datetime.utcnow -- freezing doesn't work

### ISSUE THREAD

**Issue by mindojo-victor** [spulec/freezegun#159]
I have a model with a field like:

```
timestamp = DateTimeField(required=True, default=datetime.datetime.utcnow)
```

Looks like Freezegun patches only modules and classes, so in this case time is not frozen.

**Comment by flokli** [comment]
Also got bitten by this one. I'm not sure whether it's feasible for `freezegun` to walk through imported django models, check for default attributes and replace them with methods of `FakeDatetime` (and the reverse when exiting the context), but this would be a way how to fix it.

**Comment by mindojo-victor** [comment]
Actually I am not using Django models in my case -- I use MongoEngine. I don't know if it's possible to find all references to `datetime.datetime.utcnow` in the memory.

**Comment by spulec** [comment]
I don't know of a way to make this work. I'm going to close, but feel free to reopen if there is a possible solution here.
