### ISSUE TITLE
Stop Freeze bizzare behaviour

### ISSUE THREAD

**Issue by thilakdesing** [spulec/freezegun#174]
Hi folks,

I have a util (say dateoverrider) that freezes time to a particular date (say X). I have imported this utill across my code base, so that the faketime is used on every datetime operation. 
At some point in the code, i want to go back to my original date (say O). I wrote a util (say daterestter), to stop freezer. But at this point of time, freeze_time method expects a datetime object. I don't know how to proceed from here on since my fakedate (X) is not in scope.
I tried a very stupid way of starting freeze time again with fake time, and stopping it twice. This returned my original date. But, on importing my dateoverrider util again, the freezer doesn't start.
Below is my code:

**Util dateoverrider**
from freezegun import freeze_time
freezer = freeze_time(fake_date)
freezer.start()

**Util daterestter**

from freezegun import freeze_time

freezer = freeze_time(fake_date)
freezer.start()
freezer.stop()
freezer.stop()

P.S:  I'm trying to go back to my orignal date due to pandas package. It throws me an error saying 'cannot import Nat/hashtable'.  On using my restter util, i'm able to overcome this error. The flow is as shown below.
import overrider
import resetter
import pandas
import overrider
The above flow doesnt return me error. But on importing my overrider util again, the fake time is not set.

Please correct me wherever i'm going wrong. Alternative solutions are always welcome. Please suggest

Thanks a ton,
Thilak.

**Comment by spulec** [comment]
Freezegun isn't designed to work like this. You will need to get the original freeze_time instance back to disable the freezing. Can you store the freeze_time instance as a global somehow so that it can be accessed in the place where you want to stop freezing?

**Comment by thilakdesing** [comment]
Hey Spulec,

There's a workaround using singleton class. However, i got it working by designing the util as below,

Util having start freezer at global scope.
The same Util having two classes for stopping freeze and starting again.

Thanks,
Thilak

**Comment by spulec** [comment]
No problem.
