### ISSUE TITLE
Bad display in pypi due to incorrect README.rst in release 0.3.8

### ISSUE THREAD

**Issue by sblondon** [spulec/freezegun#177]
The error is fixed in the repository but the version uploaded in pypi.python.org embeds the error. That's the reason why the page https://pypi.python.org/pypi/freezegun shows the README as pure text instead of generated html. 
You could fix it with a new release. 

For the next releases, you could check if the ReST syntax is correct with rstcheck tool:

pip install rstcheck
rstcheck README.rst

Results for README in repository and extracted from freezegun-0.3.8.tar.gz:

stephane@bearkhoff:~/src/freezegun$ ./venv/bin/rstcheck README.rst  # in git repository
stephane@bearkhoff:~/src/freezegun$ ./venv/bin/rstcheck README.arch.rst  # file in 0.3.8
README.arch.rst:97: (WARNING/2) Title underline too short.

**Comment by spulec** [comment]
Thanks, will work on getting a new release out.
