### ISSUE TITLE
Nosetests multiprocess failing for freeze_time

### ISSUE THREAD

**Issue by allentv** [spulec/freezegun#186]
Due to a large number of tests that has to be run, I usually use `--processes=4` option for nosetests to execute faster. I recently used the `freeze_time` function and it seems like the whole unit test class is skipped which I am guessing is due to some segfault. Could someone confirm if freezegun plays well with the multiprocess library or variants?

**Comment by devang-kredx** [comment]
Same issue here, this test case doesn't work well with freezetime

```
from multiprocessing import Pool

from freezegun import freeze_time
from django.test import TestCase


@freeze_time("2018-02-14 11:00:00")
class MultiProcessingTestCase(TestCase):
    """
    Test case to test if pool process of multiprocessing works
    """
    def test_multi_processing(self):
        print("POOLING")
        with Pool(processes=2) as pool:
            pass
        print("DONE")
```

**Comment by spulec** [comment]
Yes, I don't believe freezegun currently handles any of this well unfortunatley. Feel free to open a PR
