### ISSUE TITLE
Freezegun cause RequestTimeTooSkewed error for Amazon requests

### ISSUE THREAD

**Issue by pomeo92** [spulec/freezegun#188]
About an error in other env https://www.allcloud.io/how-to/how-to-fix-amazon-s3-requesttimetooskewed/

How to reproduce:

```
import boto3
with freezegun.freeze_time("2000-01-14"):
  session = boto3.Session(aws_access_key_id=<s3_access_key>,
                            aws_secret_access_key=<s3_secret_key>,
                            region_name=<region_name>)
  s3_client = session.client('s3')
  s3_client.upload_file(<input_local_file_path>, <s3_bucket_name>, <output_s3_file_path>)

```
Suggestion:
   The only way I see is to "unfreeze" time before sending request to the actual real time and then back it to the freeze state.

**Comment by spulec** [comment]
From what I can see, this is freezegun behaving in the expected manner. Yes, you will need to unfreeze if you want time to progress.

Please reopen if I am misunderstanding.

**Comment by pomeo92** [comment]
Yes its expected manner, but not desired. This makes freezegun completely useless in projects with Amazon. I'll try to change that. Just need time to understand the code of the freezegun. Thanks for response.

**Comment by ericplvn** [comment]
Has anyone figured out how to get around this? Or is there an alternate to freezegun that isn't completely useless in projects with aws
