### ISSUE TITLE
Freezegun breaks isinstance() checks on existing objects.

### ISSUE THREAD

**Issue by schinckel** [spulec/freezegun#19]
If you have a date object that was created before freezing time, you cannot then do an isinstance check against datetime.date:

```
>>> date = datetime.date.today()
>>> freezer = freeze_time('2011-01-01')
>>> freezer.start()
>>> isinstance(date, datetime.date)
False
>>>
```

This is because at the point you call the isinstance, the value of datetime.date is `<class 'freezegun.api.FakeDate'>`, of which `date` is not a subclass.

**Comment by kingbuzzman** [comment]
Any update on this? I'm running into this right now.

**Comment by schinckel** [comment]
According to my understanding, this was fixed by the referenced commit.

**Comment by kingbuzzman** [comment]
it looks like my issue is `issubclass()`

**Comment by schinckel** [comment]
It looks like there's also a `__subclasscheck__`. Should by fairly easy to follow the same pattern in the commit that @spulec referenced above.

**Comment by kingbuzzman** [comment]
How quickly can we get this merged and pushed to pypi O:)

**Comment by schinckel** [comment]
I'm not sure. It seems that @spulec hasn't been on GitHub much lately. He's likely the only one who can merge, and push releases. It is possible to reference a git-commit in a `requirements.txt`: you may have to do that until he has time to merge/push.

**Comment by boxed** [comment]
I am also a contributor that can merge. Unfortunately I can't cut releases to pypi at this time.
