### ISSUE TITLE
Does freezegun support threading.Timer and concurrent.futures.Future triggers and timeouts?

### ISSUE THREAD

**Issue by rockobonaparte** [spulec/freezegun#194]
We've been mocking time in Windows to coordinate datetime.now, time.sleep, threading.Timer triggers and concurrent.futures.Future timeouts. None of it works on Linux--likely due to different internals that don't trigger the mocks. People bring up freezegun, but we wanted to check if that's viable for handling this stuff.

I already see that time.sleep() doesn't get mocked by default, but we can route that ourselves. However, I am wondering about the rest. If freezegun is managing time, will it:

1. Start a function scheduled by threading.Timer when its delay is reached?
2. Time out a Future.result() call if the timeout threshold is reached?

**Comment by spulec** [comment]
My guess is that it won't do any of that stuff, but I can't say that I've tested it.

**Comment by spulec** [comment]
Feel free to open specific issues/PR for these
