### ISSUE TITLE
Can someone explain to me why using with_metaclass? 

### ISSUE THREAD

**Issue by wang-ye** [spulec/freezegun#200]
I am trying to understand the use of metaclass in freezegun.
When defining Fakedate, we have
class FakeDate(with_metaclass(FakeDateMeta, real_date)):

Why cannot we just do 
class FakeDate(real_date): ?
What is the benefit of introducing the with_metaclass?

Help is much appreciated.

**Comment by awbacker** [comment]
It "fakes" the`isinstance(obj, _class)` check for the `FakeDate` class when `FakeDate` is used as the class argument.  For example:

    isinstance(datetime.datetime(2017,1,1), FakeDate) -> True (but its clearly not!)

No idea why its **actually** needed or where.  I suppose you could throw an exception in there or use pdb.set_trace() and see what tests/code causes that to be executed. 

For a more complete example:
```
class F1(real_date):
    pass
class F2(with_metaclass(FakeDateMeta, real_date)):
    pass

f1 = F1(2017, 1, 1)
f2 = F2(2017, 1, 1)

>   isinstance(real_date(2017,1,1,), F2): True  # calls F2.metaclass.__instancecheck__
>   isinstance(real_date(2017,1,1,), F1): False
>   isinstance(f1, F2): True   # calls F2.metaclass.__instancecheck__
>   isinstance(f2, F2): True
```

**Comment by wang-ye** [comment]
Thanks very much. Very clear explanation @awbacker
