### ISSUE TITLE
Change frozen time when using the freeze_time decorator

### ISSUE THREAD

**Issue by ryangallen** [spulec/freezegun#206]
Is it possible to alter the frozen time in a test when using the decorator?

Thinking something like this but it doesn't work...

    @freeze_time("2017-1-14")
    class MyTests(unittest.TestCase):

        def test_changing_time(self, frozen_datetime):
            self.assertEqual(datetime.datetime.now(), datetime.datetime(2017, 1, 14))
            frozen_datetime.tick(delta=datetime.timedelta(days=10))
            self.assertEqual(datetime.datetime.now(), datetime.datetime(2017, 1, 24))

I got it to work with a context manager but I would like to avoid the indentation if the time needs to change a lot.

Thanks for your time. I'm happy to add this to the readme and make a PR if there is a way.

**Comment by spulec** [comment]
I don't believe this is currently supported. PR welcome

**Comment by spulec** [comment]
Closed with https://github.com/boxed/freezegun/commit/4a4a150481d8842b79d6ff724030190d0851f01d

**Comment by pymen** [comment]
test
