### ISSUE TITLE
freeze_time(function) fails

### ISSUE THREAD

**Issue by texnic** [spulec/freezegun#211]
The readme contains the following example:

```
def test_lambda():
    with freeze_time(lambda: datetime.datetime(2012, 1, 14)):
        assert datetime.datetime.now() == datetime.datetime(2012, 1, 14)
```

In my code, the line with `freeze_time(lambda: datetime.datetime(2017, 1, 1)):` results in an error: 

```TypeError: freeze_time() expected None, a string, date instance, or datetime instance, but got type <class 'function'>.``` 

This is caused by File "freezegun/api.py", lines 513–515: 
```
if not isinstance(time_to_freeze, (type(None), string_type, datetime.date)):
    raise TypeError(('freeze_time() expected None, a string, date instance, or '
                     'datetime instance, but got type {0}.').format(type(time_to_freeze)))
```

**Comment by spulec** [comment]
I believe that version hasn't been released yet. Will hopefully get it out soon.
