### ISSUE TITLE
Project metadata missing long description

### ISSUE THREAD

**Issue by jaraco** [spulec/freezegun#220]
When viewing the project in [PyPI (warehouse)](https://pypi.org/project/freezegun) or [PyPI (legacy)](https://pypi.python.org/pypi/freezegun), there's no long description. It would be nice if the readme were included or at least if there were a link to where the README is authoritatively hosted.

**Comment by spulec** [comment]
Added with https://github.com/spulec/freezegun/commit/62db99f67546b13280873a9e234fca92e3423905
