### ISSUE TITLE
"illegal hardware instruction" Running tests with freeze_time

### ISSUE THREAD

**Issue by rmurcek** [spulec/freezegun#222]
I'm running into an interesting issue with tests that use the @freeze_time annotation in Python 2.7.13 with freezegun 0.3.8 and 0.3.9.

During processing of this annotation, my test run is killed by the kernel with the following message:
"illegal hardware instruction".

I have no such issue in Python 3.6.

I haven't had a chance to debug yet, but I wanted to get the query out lest anyone else has encountered this one.

Thanks!

**Comment by philipCrunchboards** [comment]
I have had a similar issue, I get this error (in PyCharm):
```
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```

This is caused by the `dbm_gnu` value of `module_attribute` in:
https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L431

**Comment by 987poiuytrewq** [comment]
I am also experiencing this issue, on OSX 10.12.6 running python 2.7.13 

It looks like the issue is with `urllib3`, rather than an issue with freeze gun itself.

As a work around, you can remove the offending attribute by running the following before using freeze time

```python
from urllib3.packages.six import moves
moves.dbm_gnu = None
```

The library is for a very old unix database implementation which is pretty much unused nowadays, so should be safe to remove in this way

https://en.wikipedia.org/wiki/Dbm

**Comment by 987poiuytrewq** [comment]
Looks like this can crop up through `pkg_resources` as well, so you need to work around this as well

```python
from urllib3.packages.six import moves as urllib3_moves
from pkg_resources._vendor.six import moves as pkg_resources_moves
urllib3_moves.dbm_gnu = None
pkg_resources_moves.dbm_gnu = None
```

**Comment by spulec** [comment]
Sounds like we found a solution. Feel free to reopen if we have a script to reproduce and think Freezegun should be the one changing though.

**Comment by sliwinski-milosz** [comment]
I can reproduce this issue on macOS Sierra Version 10.12.6 and Python 2.7.13

Below you can find simple script to reproduce it:

Requirements:
```
freezegun==0.3.10
requests==2.18.4
pytest==3.5.0
```


`test.py`
```python
import requests
from freezegun import freeze_time


@freeze_time('2017-03-03')
def test_something():
    pass

```

To run it:
```
pytest test.py
```

https://github.com/spulec/freezegun/issues/222#issuecomment-365975699 workaround doesn't work for above case.

Please note that it works fine on:
1. Python 3.5.2
2. Latest requests if I will install urllib3==1.15.1 (it starts to fail on 1.16).
3. requests==2.10.0 (it starts to fail on 2.11)
4. Linux ubuntu-xenial 4.4.0-97-generic

Please let me know if you need any additional info or tests.
I am happy to help however I have no idea how to fix that issue.

**Comment by sliwinski-milosz** [comment]
I have tried on Friday to install it without binary but it didn't help.

From yesterday I do not have an access to the machine that I was able to reproduce above issue anymore.

At the moment I am on macOS High Sierra Version 10.13.4 and I can't reproduce it. That is actually a good news :)

**Comment by sfsekaran** [comment]
I'm getting this with `Python 3.6.1` and `freezegun 0.3.10`. For some reason it only causes the error when I run an entire test suite. When I run the singular test file, no error.

Furthermore, I know freezegun is the issue, because when I comment the `@freezegun.freeze_time()` decorator, the tests do execute properly.

**Comment by jmyers-skilljar** [comment]
I don't think this is a freezegun issue. I was able to reproduce without installing freezegun:

Requirements:
```
requests==2.18.4
```

main.py
```
import requests
import gdbm
```

Then run:
```
python main.py
```

I get the error when freezegun patches the various time functions in `freezegun/api.py`. Specifically, line 425: `attribute_value = getattr(module, module_attribute)` is causing the error. Somewhere down the line from that `getattr` call `requests.packages.urllib3.packages.six` is importing `gdbm`, and that causes the error.

I'm running Python 2.7.13 on OSX installed through homebrew. 
I fixed the error by reinstalling homebrew python and python@2

**Comment by sfsekaran** [comment]
@spulec 

Python Version: 3.6.1 (installed via pyenv)
OS: OSX 10.12.6

I'll get back to you with more details at some point.

@jmyers-skilljar I'll try re-installing python and see if that helps. I'm not using homebrew python, if that makes a difference.

**Comment by lucascosta** [comment]
Fixed by updating to High Sierra
