### ISSUE TITLE
freeze_time has no effect on time.clock()

### ISSUE THREAD

**Issue by gathogojr** [spulec/freezegun#228]
When you apply `@freeze_time(datetime.datetime.now())` attribute to a unit test, time is frozen if a method being invoked by the unit test uses `time.time()` but not if `time.clock()` is used

**Illustration**:
```python
import time
import datetime
from django.test import TestCase
from freezegun import freeze_time


def method1():
    start = time.clock()
    # a set of operations here
    time.sleep(0.1)
    end = time.clock()
    duration = end - start  # Doesn't always yield zero when method1 is invoked from unit test
    print duration


def method2():
    start = time.time()
    # a set of operations here
    time.sleep(0.1)
    end = time.time()
    duration = end - start  # Yields zero when method2 is invoked from unit test
    print duration


class Temp(TestCase):
    @freeze_time(datetime.datetime.now())
    def test_temp(self):
        method1()
        method2()
```

Am I missing something? I'd be eager to know if anybody has experienced similar behaviour

**Comment by colinfike** [comment]
I'm not sure I even know what the desired functionality is in this case. Since `time.clock` returns a float representing the processor time for your process since it began running (at least on Unix) would we just freeze that to `0.0`?

**Comment by spulec** [comment]
Closed with https://github.com/spulec/freezegun/pull/239
