### ISSUE TITLE
Support maya datetimes in the freezegun

### ISSUE THREAD

**Issue by rinslow** [spulec/freezegun#237]
I want to be able to freeze time with a readable `maya` datetime rather than a pythonic date time, 
for example:

```python
with freeze_time(maya.when("October 14th, 2020")):
    print(datetime.datetime.now())
```

I have implemented this and am now pushing a pull request :) 

I know you guys are using dateutil which also gives readability ,but maya is based on dateparser
why not have a broader support? :)

**Comment by spulec** [comment]
Closed with https://github.com/spulec/freezegun/pull/238
