### ISSUE TITLE
Add support for Pandas Timestamp

### ISSUE THREAD

**Issue by eyadsibai** [spulec/freezegun#242]
E   AttributeError: 'FakeDatetime' object has no attribute 'nanosecond'

**Comment by spulec** [comment]
Can you write up a minimal test case to demonstrate this?

**Comment by eyadsibai** [comment]
```import pandas as pd
df = pd.DataFrame({'column1':['2015-01-01']})
df['column1'] = pd.to_datetime(df['column1'])

@freezegun.freeze_time(datetime(2015,2,1))
def f(df):
    return df['column1'] - datetime.today()
```
the pandas version is 0.23.0, it used to work with previous versions

**Comment by spulec** [comment]
Ah, okay. This looks to be specific to [Pandas Timestamp](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Timestamp.html). We'll need to do some work to make freezegun compatible.

I don't have a particular need for this now, but happy to accept a PR if someone else has time. I'll mark this as a feature request.

**Comment by eyadsibai** [comment]
If you can show us where should we start to fix it, it would be great!
The main issue we have is that we use your library a lot with Pandas timestamp so we have two choices:
- fixing your library :)
- or stop using it.

**Comment by spulec** [comment]
I'd start by digging into the Pandas code and understand how their timestamp object works. It seems to have a `nanosecond` attribute that normal datetimes don't have so we need someway to handle that. One approach might be to add that to the attribute to our FakeDatetime.

**Comment by eyadsibai** [comment]
how come it works with normal datetime then?

**Comment by eyadsibai** [comment]
if I run the same code and remove the decorator it works!

**Comment by spulec** [comment]
I'm not positive; sounds like something to dig into.

**Comment by MartinFalatic** [comment]
I'm curious to see how this goes - it's blocking further Pandas updates.

There is also a bug open with Pandas concerning this:
https://github.com/pandas-dev/pandas/issues/21142

**Comment by danuker** [comment]
It seems just setting the `nanosecond` field to 0 works; at least in testing. I think that should do it.

But you can't set one on a `datetime.datetime` (in production).

Workaround I'll use:

```python
from freezegun.api import FakeDatetime

[...]

if isinstance(some_time, FakeDatetime):
    some_time.nanosecond = 0
[...]
```

**Comment by MartinFalatic** [comment]
Do we have an ETA of when this fix will be in a release?

**Comment by deeTEEcee** [comment]
```
class _mydatetime(datetime.datetime):
    @property
    def nanosecond(self):
        return 0

@mock.patch('pandas.datetime', _mydatetime)
class SomeUnitTest(...)
```

**Comment by MartinFalatic** [comment]
I take it that's a workaround - rather than hacking around the problem (and having to unhack it later) it would be good to have a release with this and whatever other fixes are ready to go in it).
