### ISSUE TITLE
Why doesn't `ignore` work for email.utils.formatdate?

### ISSUE THREAD

**Issue by kylegibson** [spulec/freezegun#244]
Example:

```python
    def test_foo(self):
        from email.utils import formatdate
        import ipdb
        ipdb.set_trace()
        print(formatdate())
        with freeze_time('2012-10-15', ignore=['email']):
            print(formatdate())
        assert 0
```

What's the expected behavior of the above usage of `ignore`? I'm expecting that it will not replace `time.time` inside `formatdate`, yet that appears to be what happens:

```python
> test.py(509)test_foo()
    508         ipdb.set_trace()
--> 509         print(formatdate())
    510         with freeze_time('2012-10-15', ignore=['email']):

ipdb> s
--Call--
> /usr/lib/python2.7/email/utils.py(124)formatdate()
    123 
--> 124 def formatdate(timeval=None, localtime=False, usegmt=False):
    125     """Returns a date string as specified by RFC 2822, e.g.:

ipdb> n
> /usr/lib/python2.7/email/utils.py(142)formatdate()
    141     # 2822 requires that day and month names be the English abbreviations.
--> 142     if timeval is None:
    143         timeval = time.time()

ipdb> n
> /usr/lib/python2.7/email/utils.py(143)formatdate()
    142     if timeval is None:
--> 143         timeval = time.time()
    144     if localtime:

ipdb> b 143
Breakpoint 1 at /usr/lib/python2.7/email/utils.py:143
ipdb> print time.time
<built-in function time>
ipdb> print time.time()
1527821322.89
ipdb> c
Fri, 01 Jun 2018 02:48:46 -0000
> /usr/lib/python2.7/email/utils.py(143)formatdate()
    142     if timeval is None:
1-> 143         timeval = time.time()
    144     if localtime:

ipdb> print time.time
<freezegun.api.FakeTime object at 0x7f1e2e624890> 
ipdb> print time.time()
1350259200.0
ipdb> c
Mon, 15 Oct 2012 00:00:00 -0000
```

**Comment by spulec** [comment]
`ignore` will skip the modules listed when it replaces datetime instances. Since the `formatdate` is in `__main__` at this point, it isn't going to work. You could do the import in another module and ignore that module, though that is obviously a bit hacky.

I don't think we have another way to accomplish what you are trying to do right now.

**Comment by kylegibson** [comment]
Thank you for the quick response. Here's an example that imports from another module

https://repl.it/repls/HumiliatingAcrobaticGnuassembler

**Comment by jlward** [comment]
If it helps, we are trying to interact with S3 and getting a 403 back in boto. It only happens when the S3 call is wrapped in `freeze_time`. I believe the call in boto is using `email.utils.formatdate` to generate the timestamp needed to pass along to S3 for the auth token.

**Comment by kylegibson** [comment]
Fwiw: https://github.com/boto/boto/blob/develop/boto/auth.py#L180
