### ISSUE TITLE
Add ability to exlude modules/packages

### ISSUE THREAD

**Issue by nmoran** [spulec/freezegun#258]
Would like the ability to exclude freezegun from applying to certain modules and packages. One example of this is trying to access s3 via the boto3 package.

See: [https://stackoverflow.com/questions/52061185/boto3-and-freezegun]( https://stackoverflow.com/questions/52061185/boto3-and-freezegun)

**Comment by spulec** [comment]
This exists now through the `ignore` argument, though it isn't very well documented: https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L682

**Comment by jp-u** [comment]
I had to struggle with this a little bit, but as mentioned, you can use the `ignore` kwarg to pass in a list of module strings. 

Here's an example that worked for me:
```python
from datetime import datetime, timezone
import logging

import freezegun
from pytest import LogCaptureFixture


FROZEN_TIME_STR = "2023-06-21T16:00:00+00:00"
logger = logging.getLogger()


def utc_now():
    return datetime.now(timezone.utc)


def trigger_logs():
    logger.info(f"Time Test. Now is {datetime.now(tz=timezone.utc).isoformat()}")


@freezegun.freeze_time(FROZEN_TIME_STR, ignore=["logging"])
def test_freezegun_ignore(caplog: LogCaptureFixture):
    caplog.set_level(logging.INFO)
    assert utc_now() == datetime.fromisoformat(FROZEN_TIME_STR)
    trigger_logs()
    log_rec = caplog.records[0]
    log_rec.created != FROZEN_TIME_STR
    assert FROZEN_TIME_STR in log_rec.message
```
