### ISSUE TITLE
Make package independent on the mock package unless necessary

### ISSUE THREAD

**Issue by mcepl** [spulec/freezegun#259]
[This patch](https://github.com/spulec/freezegun/files/2349478/remove_dependency_on_mock.patch.txt) makes it unnecessary to load mock package (and thus easier to deal with for packaging on Linux).

**Comment by spulec** [comment]
Can you please open as a pull request?

**Comment by mcepl** [comment]
I am a maintainer of hundreds of Python packages in openSUSE, I really don'ŧ have enough disk space and brain capacity to maintain forks for all of them.
