### ISSUE TITLE
Is there a way to get at the actual datetime when it's been frozen?

### ISSUE THREAD

**Issue by RobinRamael** [spulec/freezegun#261]
I'm trying to fix a bug in birdseye (https://github.com/alexmojaki/birdseye/issues/70) where it uses the frozen time to store the function call in its database. Because the `@eye` decorator, which is on a function somewhere, is executed in the `freeze_time` context on the unit test, it can't determine the actual time.

Is there a way around this, so that I can store the correct datetime? Can I stop the freezing for one `now()` call somehow?

**Comment by spulec** [comment]
`from freezegun.api import real_datetime`

That should work. Let me know if it doesn't.
