### ISSUE TITLE
as_arg adds frozen_time argument to front of list of arguments

### ISSUE THREAD

**Issue by taylor-cedar** [spulec/freezegun#262]
Currently the following code does not work with test classes (Django, etc). 

https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L669

That line does the following
```python
result = func(time_factory, *args, **kwargs)
```

That is incompatible with `self` being the first param to class methods and it behaves differently than most other decorators, which add their argument to the end, not the beginning.  Here is an example that doesn't work

```python
from django.test import TestCase
from freezegun import freeze_time


class MyTest(TestCase):

  @freeze_time('2016-11-01', as_arg=True)
  def test_something_with_time(self, time_factory):
    # freeze_time overrides self instead of time_factory
    # self is now the time_factory variable
    print(self) # <TimeFactory>
    print(time_factory) # <MyTestCase>
```

It should do this instead.

```python
result = func(*args, time_factory, **kwargs)
```

This is a backwards incompatible change, but will allow the decorator to be used with class based tests. Would you be open to accepting a PR that makes this breaking change?

**Comment by boxed** [comment]
It looks like you missed writing the code that doesn't work.

**Comment by boxed** [comment]
Ah, sorry, I misunderstood what you wrote before. Might I suggest that the change is instead:

```python
result = func(*args, frozen_time=time_factory, **kwargs)
```

In general I think keyword arguments are what you want anyway, since they don't have the ordering problem that this bug is about.

**Comment by taylor-cedar** [comment]
@boxed I am completely agree about keyword argument versus positional arguments. They are generally much easier to use. I almost always use keyword arguments in my personal code.

There are 2 problems I see with this approach though:
1. It behaves different from other decorators. All other decorators I have seen in Python use positional arguments. I think consistency is more important
2. It forces people to name their argument `frozen_time`. Some people may not like that, but it also forces people to look in the docs to know the argument name or just try a random name and look at the error.

What are your thoughts?

**Comment by boxed** [comment]
1. Well there are many that use keyword arguments. Pytest for example uses this heavily.
2. I don't see a problem with that. 

There is a backwards compatibility issue here too I guess... but that can be worked around with a little bit of inspect magic and a deprecation warning.

**Comment by boxed** [comment]
Pytest fixtures work by inserting (and knowing what to insert!) by the name of the parameter. 

Re 2. absolutely, but it's a bit unlikely so shouldn't be a real concern.

**Comment by boxed** [comment]
I've thought this through a bit more now, and think it's better with a new as_kwarg option. Then there is no backwards compatibility problem and it's a bit more elegant too I think. What do you think?

**Comment by 0xpsilocybe** [comment]
Hi all,
I also faced the same problem in my Django project. In my opinion a new `kwarg` is a better solution, as it is less likely to break backwards compatibility, thus you could release this patch in a minor version.
If there is a need in the future to move positional argument between `*args` and `**kwargs`, it can be released in a major version which can have breaking changes.

**Comment by boxed** [comment]
@taylor-cedar I can do more than that. I have commit access ;)

But I'm spending most of my time on my mutation tester right now so might not get around to this for a while. I have some vague ideas of blowing some days on freezegun at some point... 

If anyone submits a good PR I can merge it pretty fast though.

**Comment by jmichelsen** [comment]
@boxed I ran across another bug in the freeze_time decorator related to the `as_arg` param, and your PR fixes it, inadvertently. Any chance we can get your PR pushed forward and merged soonish?

**Comment by boxed** [comment]
Sure. I just can't roll a release. But we can bug @spulec for that until he gives me release access ;)

**Comment by belkka** [comment]
I wanted to suggest to add `as_last_arg` argument, which allows to keep backward compatibility, but `as_kwarg` seems even better!

BTW, following works:
```
class MyTestCase(TestCase):
    @freeze_time(as_arg=True)
    def test_something(frozen_time, self):  # sic!
        ...
```

**Comment by WisdomPill** [comment]
@boxed Any news on `as_kwarg`?

**Comment by boxed** [comment]
I haven't made it. I would welcome a PR. Seems like it should be an easy change.
