### ISSUE TITLE
Python 2.7 build failure

### ISSUE THREAD

**Issue by sanjayankur31** [spulec/freezegun#279]
While building 0.3.11 in a clean py2 virtual environment, the build fails:

```
creating build/bdist.linux-x86_64/egg/freezegun
copying build/lib/freezegun/api.py -> build/bdist.linux-x86_64/egg/freezegun
copying build/lib/freezegun/__init__.py -> build/bdist.linux-x86_64/egg/freezegun
copying build/lib/freezegun/_async.py -> build/bdist.linux-x86_64/egg/freezegun
byte-compiling build/bdist.linux-x86_64/egg/freezegun/api.py to api.pyc
byte-compiling build/bdist.linux-x86_64/egg/freezegun/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/freezegun/_async.py to _async.pyc
  File "build/bdist.linux-x86_64/egg/freezegun/_async.py", line 12
    result = yield from coroutine(time_factory, *args, **kwargs)
                      ^
SyntaxError: invalid syntax

creating build/bdist.linux-x86_64/egg/EGG-INFO
```

**Comment by Hanaasagi** [comment]
From your feedback, I see `byte-compiling`. It's the behavior of builing a egg format distribution.

In a egg dist, bytecode is required, and source code is optional(`--exclude-source-files`). So it need to compile to generate `.pyc` file, when building. And `yield from` expression is Introduced in Python3, [PEP 380](https://docs.python.org/3/whatsnew/3.3.html#pep-380).

Maybe you can try `python setup.py sdist bdist_wheel`

> Wheel is an installation format; egg is importable. Wheel archives do not need to include .pyc and are less tied to a specific Python version or implementation. Wheel can install (pure Python) packages built with previous versions of Python so you don’t always have to wait for the packager to catch up.

More detail, please see:
[The Quick Guide to Python Eggs](http://peak.telecommunity.com/DevCenter/PythonEggs)

**Comment by sanjayankur31** [comment]
All I've run here is `python setup.py build; python setup.py install`. That is, as far as I know, the correct procedure for installing python modules. The `_async` module used here is Python3 only, which is what's causing the error in a python2 environment. The fix/workaround is to remove that particular file befure running the above commands.

**Comment by Hanaasagi** [comment]
I produce above error message in `python setup.py install`. By default, `python setup.py install` will compile `.py` to `.pyc`

Maybe this can help you
```
python setup.py install --no-compile
```

I have tested in docker

```Dockerfile
FROM python:2.7


RUN git clone https://github.com/spulec/freezegun.git
RUN cd freezegun && \
    git checkout 0.3.11 && \
    python setup.py build && \
    python setup.py install --no-compile
```

**Comment by sanjayankur31** [comment]
Thanks for that. The Fedora build system requires that the libraries be byte-compiled. So `--no-compile` won't work for us. I'll close this ticket now, since we have a workaround in place.
