### ISSUE TITLE
Remove nose dependency

### ISSUE THREAD

**Issue by mcepl** [spulec/freezegun#280]
nose seems to me mostly obsolete and dead project (even its own maintainers seem to move to its successor). Moreover, it seems to be mostly unnecessary now, at least as far as the code itself is concerned by API provided by the very standard library of Python even in the version 2.7. Therefore, dependency on nose is no longer necessary and thus advisable.

This attached patch suggests removal of this dependency.

Thank you for considering this issue.

[denose.patch](https://github.com/spulec/freezegun/files/2745811/denose.patch.txt)

**Comment by boxed** [comment]
Nose is already gone.

**Comment by boxed** [comment]
We use pytest now. It's much nicer than nose and a lot nicer than the standard lib stuff.

**Comment by perobertson** [comment]
The latest release on pypi is still 0.3.11 which uses nose. There are a couple good features that would be good to release so I opened up a PR to make 0.3.12 https://github.com/spulec/freezegun/pull/278

**Comment by mcepl** [comment]
@boxed lovely, so make a release and I can use it for openSUSE.

**Comment by boxed** [comment]
I can't unfortunately. I can commit to this repo but don't have access to make a release on pypi. 

@spulec has to do it

**Comment by mcepl** [comment]
@spulec It has been mostly fixed, but there is still ``tests_require = ['mock', 'nose']`` in ``setup.py``.
