### ISSUE TITLE
strftime 2nd argument TypeError

### ISSUE THREAD

**Issue by dimaqq** [spulec/freezegun#282]
I've got some code that uses `time.strftime("%Y")`.

This code works on its own, but fails under pytest + pytest-freezegun (+freezegun) + flaky (not sure if that matters).

I think I've tracked it down to this:

```py
# freezegun/api.py
def fake_strftime(format, time_to_format=None):
    if time_to_format is None:
        if not _should_use_real_time():
            time_to_format = fake_localtime()

    return real_strftime(format, time_to_format)
```

Thus, under some circumstances (not sure which), `time_to_format` may be `None`.

While the function behaviour on Python 3.7.2 is like this:

```py
In [1]: import time

In [2]: time.strftime("%Y", None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-db4c2a5b7f22> in <module>
----> 1 time.strftime("%Y", None)

TypeError: Tuple or struct_time argument required

In [3]: time.strftime("%Y")
Out[3]: '2019'
```

In other words, `None` cannot be passed to `strftime`.

**Comment by boxed** [comment]
Yep, the fix was what I thought. Thanks for the report!
