### ISSUE TITLE
Support for calendar.timegm()

### ISSUE THREAD

**Issue by timofurrer** [spulec/freezegun#287]
It would be awesome to support [`calendar.timegm()`](https://docs.python.org/3.7/library/calendar.html#calendar.timegm).

It's actually the inverse of `time.gmtime()` which is currently supported and frozen properly.

**Comment by spulec** [comment]
Thanks; setting as a feature request.

**Comment by itajaja** [comment]
this was wrong. `gmtime`'s argument is optional so it's not a purely deterministic function. `timegm` is instead a pure function and should not be patched by freezegun.
