### ISSUE TITLE
Add ability to perform arithmetic on FakeDate/FakeDateTime objects

### ISSUE THREAD

**Issue by sahutd** [spulec/freezegun#302]
For example:
I am trying to find out the number of days between today(frozenTime) and some date, i get the following error

`interval =(datetime.date.today()-dueDate)`

> unsupported operand type(s) for -: 'FakeDate' and 'FakeDatetime'

Whereas without freezegun(aka actual Python datetime lib)

`
>>> a = datetime.date(day=2, month=3, year=2019)
>>> b = datetime.date.today()
>>> a - b
datetime.timedelta(-106)
`

**Comment by wassimwazzi** [comment]
Was this addressed? I am running into the same issue
