### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by JoseKilo** [spulec/freezegun#303]
Using python3.8, with `-Werror`

```python
>>> from freezegun import freeze_time
>>> @freeze_time()
... async def foo():
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "[...]/.tox/py38-std-sha256/lib/python3.8/site-packages/freezegun/api.py", line 500, in __call__
    return self.decorate_coroutine(func)
  File "[...]/.tox/py38-std-sha256/lib/python3.8/site-packages/freezegun/api.py", line 689, in decorate_coroutine
    return wrap_coroutine(self, coroutine)
  File "[...]/.tox/py38-std-sha256/lib/python3.8/site-packages/freezegun/_async.py", line 9, in wrap_coroutine
    def wrapper(*args, **kwargs):
  File "/opt/python/3.8-dev/lib/python3.8/asyncio/coroutines.py", line 111, in coroutine
    warnings.warn('"@coroutine" decorator is deprecated since Python 3.8, use "async def" instead',
DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
```

According to the release notes:
https://docs.python.org/3.8/whatsnew/changelog.html#changelog

> bpo-36921: Deprecate `@coroutine` for sake of async def.

**Comment by tirkarthi** [comment]
One note is that the freezegun supports 3.4 which reached EoL. `async def` syntax is supported only from 3.5 and above

**Comment by spulec** [comment]
Based on some quick research, it doesn't seem like there is an easy way to solve this without dropping support for anything before 3.5. I don't mind dropping support for 3.4, but dropping support for 2.7 is not preferred.

I'm open to any ideas.

**Comment by eric-weaver** [comment]
I put up #316 as an attempt to fix this issue. Let me know if this makes sense

**Comment by spulec** [comment]
This should be fixed with https://github.com/spulec/freezegun/pull/316. Let me know if you see other issues.

**Comment by FedericoCeratto** [comment]
Related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944026
