### ISSUE TITLE
`as_arg` explanation in docs?

### ISSUE THREAD

**Issue by startakovsky** [spulec/freezegun#304]
Hi,

What does the optional argument `as_arg` do in the `freeze_time` function?

Thanks,
Steven

**Comment by startakovsky** [comment]
Fire argument? Oh, like first argument? And otherwise, it will just be what
is returned when datetime.now() is called?

**Comment by boxed** [comment]
Sorry autocomplete! Yes first. As opposed to it not being passed at all. You need it to be passed if you want to manipulate it. Mostly you don't so then you don't care about having it passed in.

**Comment by startakovsky** [comment]
thanks!
