### ISSUE TITLE
Cannot mock attributes

### ISSUE THREAD

**Issue by meyt** [spulec/freezegun#306]
The `datetime` assigned to an attribute cannot mock by freezegun. here is a example that describes the issue. 

```python
from freezegun import freeze_time
from datetime import datetime


class A:
    my_attr = datetime.utcnow

    def my_func(self):
        return datetime.utcnow


expected_date = datetime.utcnow().replace(year=2001)
with freeze_time(expected_date):
    a = A()
    print(a.my_func()())
    print(a.my_attr())

```

Result
```
2001-07-14 19:26:05.653150
2019-07-14 19:26:05.671282
```

---

p.s: I found it where working with `sqlalchemy` field default argument and it doesn't work:

```python
created_at = Field(
    DateTime,
    default=datetime.utcnow,
    nullable=False
)
```

but it works if i wrap it into a function:

```python
created_at = Field(
    DateTime,
    default=lambda: datetime.utcnow,
    nullable=False
)
```

**Comment by boxed** [comment]
This is an unfortunate consequence of how python works. You can handle this by making sure freezegun is initialized before the import of the file you first quote here.
