### ISSUE TITLE
Add mypy types (or type stubs)

### ISSUE THREAD

**Issue by ska-kialo** [spulec/freezegun#318]
Hi,

my colleague(s) and I are currently working on writing (a subset of) type stubs for freezegun and we were wondering if it would make sense to contribute them.

Going by the [contribution guide for typeshed](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library) the first step in the process is asking the maintainers of the libraries if they want to integrate the type hints into the library directly.
What is your opinion on this?

Contributing the types here could be done one of the following ways:

- adding the types as separate stub files
- adding the types in the code as annotations (this isn't compatible with Python 2)
- adding the types as type comments (compatible with Python 2 and 3)

**Comment by boxed** [comment]
I think adding them as annotations is the way to go. We are going to drop python 2 support for new versions at year end anyway. Or at least I think we should :P

@spulec what do you think?

**Comment by boxed** [comment]
I'm fine with this too. People who are on python 3 are mostly on 3.5+ anyway and if they need it for older versions they can use older versions of freezegun.

**Comment by spulec** [comment]
Works for me

**Comment by sbdchd** [comment]
Type stubs were recently added to the type shed, although it's preferable to keep them in the project itself

https://github.com/python/typeshed/pull/4425
