### ISSUE TITLE
FakeSleep ?

### ISSUE THREAD

**Issue by stuaxo** [spulec/freezegun#332]
Could freezegun provide something so that calls to sleep could be faked ?

The fake time would advance during sleep statements, but a real delay would not happen.

This would make it a lot easier to test code that calls sleep() for delays (and usually tests how much time has passed).

**Comment by boxed** [comment]
That sounds like a very good suggestion!

**Comment by stuaxo** [comment]
I've found for testing ratelimiting, I need to this and it's opposite:  a way of time advancing by a set amount every call

It could work like this:

```python
with fakesleep(seconds=100):
    sleep()
    # no delay occurs.
```

```python
with fakesleep(seconds=100):
    sleep()
    # no delay occurs, fake time will have advanced 100 seconds
    sleep()
    # no delay occurs, fake time will have advanced 100 seconds
```

**Comment by stuaxo** [comment]
I found an actual `fakesleep` module immediately after writing this request, I still think something like this built into freezegun would be a good fit.

**Comment by stuaxo** [comment]
(accidentally clicked close ! )

**Comment by spulec** [comment]
If there is already another module that does this, I'm a bit hesitant to combine them. Maybe add a note in our docs so people know about the other module?

**Comment by stuaxo** [comment]
OK, I put a small PR there, it will be interesting to see if that project is alive.

**Comment by spulec** [comment]
Sounds good. If that project seems dead, feel free to post back here and it may make sense to discuss again.
