### ISSUE TITLE
requires dateutil ~=2.7.0

### ISSUE THREAD

**Issue by liverpool1026** [spulec/freezegun#333]
https://github.com/spulec/freezegun/pull/328/files

This PR imports dateutil and is using dateutil.tz.UTC, which is introduced in dateutil 2.7 and will break for any 2.x (x < 7). 

Currently dependency only checks for >2.0. Suggestion to update setup.py to change from requires += ['python-dateutil>=2.0'] to requires += ['python-dateutil>=2.7']

**Comment by spulec** [comment]
Done; thanks!
