### ISSUE TITLE
freezegun 0.3.15 requires python-dateutil >= 2.7

### ISSUE THREAD

**Issue by wc-s** [spulec/freezegun#337]
This line in the recent freezegun release: https://github.com/spulec/freezegun/compare/0.3.14...0.3.15#diff-80ef255f3bb85cfd652668d719317c10R26

It requires python-dateutil >= 2.7 https://github.com/dateutil/dateutil/pull/497/files#diff-d557f7d74e4fc13a70a1f2fed348f553R5

However, this is not reflected in `setup.py`.

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/freezegun/commit/f64281d4a0b5e7ec4c870eed8ebcbb3c6ad50305
