### ISSUE TITLE
request: 0.1.19.1 release with dateutil require fixed

### ISSUE THREAD

**Issue by AdamWill** [spulec/freezegun#338]
OK, this is a very specific request, but it'd really help me...

I am trying to maintain some stuff that I want to work on RHEL 7. RHEL 7 has freezegun 0.1.19. So I'd like to set up a tox environment which specifically pulls in that freezegun, to check my code will run with it (I have already found that 0.1.19 had a bug which broke pytest if you used the `freeze_time` decorator along with a pytest fixture, for instance).

Unfortunately, I can't, because of the bug fixed later by https://github.com/spulec/freezegun/commit/15c7cc3cf1599efa65896e7138f3015e68ae5998 . If you try and specify `freezegun == 0.1.19` in the requirements, pip blows up on the logically-impossible dateutil requirement in freezegun 0.1.19's `setup.py`.

So...could you possibly cut a 0.1.19.1 release which would be just 0.1.19 plus that fix? That would help me out quite a lot :) Thanks!

**Comment by spulec** [comment]
Done!

https://pypi.org/project/freezegun/0.1.19.1/

**Comment by AdamWill** [comment]
belated thanks very much! :)
