### ISSUE TITLE
dateutil.tz has no attribute UTC

### ISSUE THREAD

**Issue by vinimmelo** [spulec/freezegun#341]
I've encountered this issue after installing freezegun in my project and try to run in my tests:

```
    _EPOCHTZ = datetime.datetime(1970, 1, 1, tzinfo=dateutil.tz.UTC)
AttributeError: module 'dateutil.tz' has no attribute 'UTC'

```
All the dependencies is update with the last modification.

**Comment by vinimmelo** [comment]
After i change the `api.py` file in line 26 to this:
`_EPOCHTZ = datetime.datetime(1970, 1, 1, tzinfo=dateutil.tz.tzutc())`

All works smoothly.
I send the PR to fix this, maybe this was a problem only in my machine, so we should verify if that is not the case before :sweat_smile:

**Comment by vinimmelo** [comment]
## Solution
`python-dateutil` (2.6.1) was not in the latest version, after the upgrade all works fine.

**Comment by boxed** [comment]
No problem.
