### ISSUE TITLE
'dateutil.tz' has no attribute 'UTC'

### ISSUE THREAD

**Issue by Zujiry** [spulec/freezegun#349]
I have the following top_level error when using freezegun:

```
../../venv/lib/python3.8/site-packages/freezegun/__init__.py:9: in <module>
    from .api import freeze_time
../../venv/lib/python3.8/site-packages/freezegun/api.py:26: in <module>
    _EPOCHTZ = datetime.datetime(1970, 1, 1, tzinfo=dateutil.tz.UTC)
E   AttributeError: module 'dateutil.tz' has no attribute 'UTC'
```

Is there a solution for this? I am using Python 3.8

**Comment by boxed** [comment]
What version of dateutil do you have? I have python-dateutil==2.8.0 locally and there that works.

**Comment by Zujiry** [comment]
That fixes it 👍 , sorry for not checking that beforehand

**Comment by boxed** [comment]
No problem at all. Glad it worked out.
