### ISSUE TITLE
freeze_time doesn't affect class variables declared outside of functions

### ISSUE THREAD

**Issue by ntbloom** [spulec/freezegun#355]
freezegun 0.3.15 with Python 3.8.3 on Fedora 32.

The freeze_time method doesn't appear to have any effect on class variables that are declared outside of function calls or a constructor.  This is primarily a problem when using `typing.NamedTuple` classes. See the following code snippet for a complete demonstration of the bug:

```python3
from freezegun import freeze_time
from time import time, gmtime
from typing import NamedTuple, Optional


class Timekeeper1:
    def __init__(self):
        self.year = gmtime(time())[0]


class Timekeeper2(NamedTuple):
    year: Optional[int] = gmtime(time())[0]


class Timekeeper3:
    year = gmtime(time())[0]


if __name__ == "__main__":
    with freeze_time("1999-12-31"):
        t1 = Timekeeper1()
        assert t1.year == 1999, "error with __init__ variant"  # passes

        t2 = Timekeeper2()
        assert t2.year == 1999, "error with NamedTuple variant"  # fails

        t3 = Timekeeper3()
        assert t3.year == 1999, "with plain class variant"  # fails
```

**Comment by xmo-odoo** [comment]
By the time you reach `__main__` the classes have already been created, meaning their attributes have alreday been initialised. freezegun could hardly reach back in time to re-set attributes based on calls predating its activation.

**Comment by boxed** [comment]
This is not just by design but it's by design of the python language. You could argue it's a design flaw (and I would probably agree!) but it can't be handled.
