### ISSUE TITLE
[fyi] stubs for freezegun were submitted to typeshed 

### ISSUE THREAD

**Issue by hauntsaninja** [spulec/freezegun#365]
Type stubs for this library were submitted to typeshed in https://github.com/python/typeshed/pull/4425

You don't need to take any action, but:
a) If you wish to include type stubs as part of your package, we're happy to transfer them to this repo (or potentially aid with the addition of inline types)
b) If you want us to remove the stubs from typeshed, we will!

**Comment by spulec** [comment]
Thanks for opening this!

No need to remove them, but it would be great to eventually move them to this repo. Are there docs somewhere for how best to do that?

**Comment by dcfranca** [comment]
After upgrading to mypy 0.7.9 I started getting the following error:
`error: Module 'freezegun.api' has no attribute 'FakeDate'`

Is this somehow related to this issue?
