### ISSUE TITLE
New release to remove six dependency ?

### ISSUE THREAD

**Issue by Djailla** [spulec/freezegun#366]
Hello,

Is there a plan to publish a new release of freezegun to PyPi soon ?

Regards

**Comment by epicfaace** [comment]
I'd also like this as it would give me the fix in #353. @spulec , could you take a look whenever you get a chance? (no rush)

**Comment by spulec** [comment]
Since this release is dropping Py2 support, I decided to make it a major release and make it version `1.0.0`!

![](https://i.giphy.com/media/kyLYXonQYYfwYDIeZl/200.gif)
