### ISSUE TITLE
Mention pytest in README?

### ISSUE THREAD

**Issue by cdeil** [spulec/freezegun#367]
This looks great!

I presume this works with pytest?

If yes, could you please mention that in the README?
E.g. this near the top would have helped me quickly gather whether it's something I should try or not.
"freezegun works with pytest and unittest."

**Comment by boxed** [comment]
Why though? It works with python. Pytest and unittest are python...

**Comment by cdeil** [comment]
Of course if you think its obvious, just close the issue and keep as-is.

I think it would be useful just to be crystal-clear to beginners in Python (and help Google search point to this package for "pytest mock datetime", not sure if this works via README content), or for me it wasn't obvious because pytest does a lot of magic with fixtures and decorators, and it's not obvious that your decorator is compatible with pytest itself or even other packages like https://hypothesis.readthedocs.io/ that are used via decorators on test functions.

**Comment by boxed** [comment]
Hmm.. you have a strong point. How about changing this example code: https://github.com/spulec/freezegun#decorator to just add a comment `# A pytest style tests:" for the first test?

**Comment by cdeil** [comment]
@boxed - sounds good. See #368.
