### ISSUE TITLE
Incorporate improvements from Typeshed

### ISSUE THREAD

**Issue by mwgamble** [spulec/freezegun#425]
I noticed that built-in types have been added to this package, which is a huge :+1: 

However I noticed that since that has been done, there have been some improvements in the Typeshed typing files. These still exist because there hasn't been a formal release of freezegun with the type hints included.

Examples include this, which make the type hinting stricter (and therefore more useful):

https://github.com/python/typeshed/pull/6164

It would be great to see these improvements included before a new release is made.

**Comment by bblommers** [comment]
Freezegun 1.5.0 now has inline types, so I think this is no longer relevant.
