### ISSUE TITLE
Replace distutils.version with packaging.verison.path

### ISSUE THREAD

**Issue by pquentin** [spulec/freezegun#428]
Using the pytest plugin on 3.11 (but 3.10 too) gives the following warning:

```
/home/runner/work/urllib3/urllib3/.nox/test-3-11/lib/python3.11/site-packages/pytest_freezegun.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
```

One option to fix this is to use packaging.version.path: https://github.com/python-pillow/Pillow/pull/4797/files

cc @hugovk @jdufresne

**Comment by hugovk** [comment]
I was wondering why I couldn't reproduce this, and then couldn't find the `pytest-freezegun==0.4.2` version that urllib3 uses, and then noticed it's another library entirely!

This is [freezegun](https://pypi.org/project/freezegun/), and that warning is from [pytest-freezegun](https://pypi.org/project/pytest-freezegun/) => https://github.com/ktosiek/pytest-freezegun

**Comment by pquentin** [comment]
Sorry about that. Thanks @hugovk for the help here!
