### ISSUE TITLE
Type annotations for as_kwarg are confusing

### ISSUE THREAD

**Issue by WesleyAC** [spulec/freezegun#442]
I'm trying to use freezegun with the types-freezegun package, which it looks like is maintained here? But let me know if I should file elsewhere. I have:

```python3
import unittest
import freezegun

class TestFoo(unittest.TestCase):
    @freezegun.freeze_time("1969-07-20 00:00:01", tz_offset=0, as_kwarg="frozen_time")
    def test_foo(self, frozen_time: freezegun.api.FrozenDateTimeFactory) -> None:
        # my test code here
```

But mypy complains:

```
my_test.py:6: error: Type of decorated function contains type "Any" ("Callable[..., None]")
```

I'm not super familiar with mypy, so perhaps I'm missing something obvious, but from poking around at the type bindings, I can't figure out how I'm supposed to get this working. Anyone know how this is possible?

Thanks!

**Comment by hhartzer** [comment]
I'm interested in this as well. Did you ever find a resolution?

**Comment by bblommers** [comment]
Freezegun 1.5.0 has proper types now, so I'm assuming this is fixed. Let us know if you're still running into issues though.
