### ISSUE TITLE
Stubs missing from 1.2.0 package

### ISSUE THREAD

**Issue by g-as** [spulec/freezegun#443]
Hi,

once installed, I cannot seem to find the newly added .pyi stub files.

I feel
```
[options.package_data]
freezegun = py.typed, *.pyi
```
is missing from `setup.cfg`

**Comment by gitpushdashf** [comment]
Getting this as well. Related: #403

**Comment by g-as** [comment]
👍

**Comment by gitpushdashf** [comment]
It works! Thank you so much!
