### ISSUE TITLE
ipdb stops showing prompt text after carriage return when using freeze_time

### ISSUE THREAD

**Issue by Phil-Barber** [spulec/freezegun#450]
0Details and recreation found here:

https://stackoverflow.com/questions/71584885/ipdb-stops-showing-prompt-text-after-carriage-return

My own debugging has shown that with tick=True or auto_tick_seconds>0 the problem goes away which for me points to the `FrozenDateTimeFactory` because of [this block](https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L620)

But this is the first time I've looked at this and ran out of ideas almost immediately 😅 

I'll try looking again some time because it's a really annoying problem to have but opening the issue so it's at least recorded

FWIW the issue only occurs inside the context manager:
```
def test_freeze_time_ipdb():    
        __import__("ipdb").set_trace()  # can see prompt here
        with freeze_time("2021-01-01T12:00:01"):
            print('nothing')  # prompt no longer visible
        assert False  # can see prompt again
```

I've also identified that with tick=True or auto_tick_seconds>0 commenting out the `+(real_datetime.now() - self.start)` or `self.tick()` in the respective call methods causes the issue too

**Comment by shangxiao** [comment]
Can confirm issue with freezegun 1.2.1, ipdb 0.13.9 & pytest 7.1.2 👍

pdb works fine

**Comment by shangxiao** [comment]
Also can confirm the PR above works for me 👍
