### ISSUE TITLE
Add FakeDate to stubs

### ISSUE THREAD

**Issue by srittau** [spulec/freezegun#488]
I'm using pysqlite3 instead of the built-in sqlite3 module, since I need newer features. Therefore I need to register `FakeDate` manually as an adapter for pysqlite3. Unfortunately, since `FakeDate` is not defined in `freezegun/api.pyi`, my type checkers complain about it. It would be useful to include `FakeDate` (and potentially other fake classes) in the type stubs.

**Comment by finswimmer** [comment]
Hey,

I second this. My use case is, that I write a custom representer for `FakeDate` in `pyyaml`.

Thanks a lot for this really cool project :+1:

**Comment by bblommers** [comment]
Freezegun 1.5.0 has proper (in-line) typing support, so I believe this is fixed.
