### ISSUE TITLE
1.2.2: missimg git tag

### ISSUE THREAD

**Issue by kloczek** [spulec/freezegun#490]
https://pypi.org/project/freezegun/ shows that latest version is 1.2.2 however here there is no git tag for that version.
My automation is using git tags.
Is it possible to add missing git tag? .. please 🤔

**Comment by boxed** [comment]
Duplicate of #468

**Comment by boxed** [comment]
I would in general recommend you to move to time-machine.

**Comment by kloczek** [comment]
> I would in general recommend you to move to time-machine.

Hmm .. what you mean? 🤔

**Comment by boxed** [comment]
https://github.com/adamchainz/time-machine is better than freezegun in every way I believe.
