### ISSUE TITLE
Doesnt change the time for subprocess

### ISSUE THREAD

**Issue by scentedwax** [spulec/freezegun#505]
I need to change time in that subprocess:

`testfile = open("testfile.txt", "w")`
`with freeze_time("2012-01-14"):`
`    sr = subprocess.Popen(["print_time"], stderr=testfile, stdout=testfile))`
`testfile.close()`

So, "print_time" doesnt return desired time for me

**Comment by paketb0te** [comment]
Since `subprocess.Popen()` can execute arbitrary binaries on the OS level, I don't think there is a reasonable way to handle this case in freezegun.

I think one would have to manipulate the actual host OS system time to achieve this, which I would _strongly_ advise against...

**Comment by bblommers** [comment]
@scentedwax I understand how it can be useful, but it is out of scope as far as I'm concerned. This library is specifically about mocking the `datetime` module - mocking the host system time is a whole different animal.
