### ISSUE TITLE
Maintenance plans

### ISSUE THREAD

**Issue by jaraco** [spulec/freezegun#516]
According to https://github.com/spulec/freezegun/pull/511, this project is abandoned.

Would the former maintainers (@spulec) consider handing off this project so others can maintain it? I'd be open to maintaining it. If you want to attempt that, feel free to add me as an owner in PyPI and optionally consider transferring the repo to me.

For me, switching to `time-machine` is not simple because I'd like to rely on pytest-freezer and it would need to be ported.

**Comment by Dreamsorcerer** [comment]
> For me, switching to `time-machine` is not simple because I'd like to rely on pytest-freezer and it would need to be ported.

We're also getting reports of segfaults with time-machine, so it seems a lot less reliable than freezegun. Would be good to have the project revived.

**Comment by Dreamsorcerer** [comment]
I'd suggest getting a second person added as a backup, so we don't end up in this position again. @jaraco contributes to a lot of Python projects, including cpython itself, so is certainly qualified to help.
