### ISSUE TITLE
Freezegun doesn't mock pointers to date functions

### ISSUE THREAD

**Issue by dannysepler** [spulec/freezegun#523]
_Note: I'm not sure if this is an extension of the [mutable defaults disclaimer](https://github.com/spulec/freezegun#default-arguments) in the README. Feel free to close if so!_

It seems that if a pointer to a datetime function already exists, freezegun won't mock it. Using pointers to datetime functions can be a common pattern in ORMs such as peewee, where it may be used to define a field's default. [Example Stackoverflow](https://stackoverflow.com/a/33314937).

Here are a few reproductions (on freezegun v1.3.1):

```python
from freezegun import freeze_time
from datetime import date

class Model:
    today = date.today

    def get_today(self):
        return date.today()

class TestFreezegun:
    @freeze_time('2013-04-09')
    def test_this_fails(self):        
        model = Model()
        # This mocks successfully
        assert date(2013, 4, 9) == model.get_today()
        # This fails
        assert date(2013, 4, 9) == model.today()

    def test_this_also_fails(self):        
        today = date.today
        with freeze_time('2013-04-09'):
            assert today() == date.today()
```

**Comment by bblommers** [comment]
Hi @dannysepler, that has indeed the same root cause as what the Mutable Defaults section describes.

As far as I know, you can circumvent this behaviour by using local imports, so by making sure that the `Model.today` field is only initialized when `freezegun` is active.

```
class TestFreezegun:
    @freeze_time('2013-04-09')
    def test_this_succeeds_with_local_import(self):
        from .. import Model
        model = Model()
        # This mocks successfully
        assert date(2013, 4, 9) == model.get_today()
        # This fails
        assert date(2013, 4, 9) == model.today()
```
