### ISSUE TITLE
tests/utils.py seems to be missing from the 0.2.8 tarball

### ISSUE THREAD

**Issue by keszybz** [spulec/freezegun#75]
Tests fail with
```
ImportError: cannot import name 'utils'
```

**Comment by spulec** [comment]
I had not intended for the tests to be included with the distributions. That is now fixed with d8df201256de7013b04ea57d8c4f1878787b0fe8.

Thanks.

**Comment by keszybz** [comment]
Hm, but why? Running tests is a nice way to check that things are OK. Not just in freezegun itself, but e.g. in dependencies.

**Comment by spulec** [comment]
[This](https://github.com/spulec/freezegun/issues/27) was the original reason. I'm open to alternative suggestions, but tend to be -0 on things like a nested tests directory inside of the freezegun module.

**Comment by pypingou** [comment]
You can ship the tests in the tarball without nesting them in the module itself (because they should not be installed) which is what you do now, thanks for that! :)

**Comment by keszybz** [comment]
I think that #27 was bogus. If I revert HEAD (so I'm effectively at freezegun@7da4cef779),
```
pip install .
```
does not install tests. Neither does
```
pip install freezegun==0.2.8
```
Neither does
```
python setup.py install --user
```
Nor
```
python setup.py sdist
pip install `pwd`/dist/freezegun-0.2.8.tar.gz --user  
```
I think that the reporter from #27 might have had an old egg in his git checkout directory.
