### ISSUE TITLE
Freezegun does not affect time.strftime

### ISSUE THREAD

**Issue by calpaterson** [spulec/freezegun#76]
Freezegun doesn't affect time.strptime, which still returns the current time.  I know you don't claim to affect this method in the README, but it might but helpful to others if you could mention explicitly that you don't:

```
import unittest
import time

from freezegun import freeze_time

class TestStrptime(unittest.TestCase):

    @freeze_time("2012-01-14 12:00:01")
    def test_strptime(self):
        self.assertEquals(time.strftime("%Y"), "2012")
```

**Comment by spulec** [comment]
Ah, I missed one!

Thanks for opening. I'll try to get around to fixing this. If anyone else gets a minute and wants to take a stab at a pull request, feel free.

**Comment by spulec** [comment]
I've added support for `time.strftime`, `time.localtime`, and `time.gmtime` with #78.

If you can give it a test on your end, I'll update the docs and push out a new release.

**Comment by spulec** [comment]
Pushing out a new release now. Feel free to reopen if things don't seem to work.
