### ISSUE TITLE
Problem with dependency specification for `python-dateutil` .. ?

### ISSUE THREAD

**Issue by paulfurley** [spulec/freezegun#79]
Hey, not quite sure what's going on here, but my `pip install` is failing on Travis on this package:

```
Collecting python-dateutil<2.0,>=1.0,>=2.1 (from freezegun==0.1.18->-r measurement_collector/downloaders/ea_rivers_and_sea_levels/requirements.txt (line 3))

Could not find a version that satisfies the requirement python-dateutil<2.0,>=1.0,>=2.1 (from freezegun==0.1.18->-r measurement_collector/downloaders/ea_rivers_and_sea_levels/requirements.txt (line 3)) (from versions: 1.4, 1.4.1, 1.5, 2.1, 2.2, 2.3, 2.4.0)

Some externally hosted files were ignored as access to them may be unreliable (use --allow-external to allow).

No distributions matching the version for python-dateutil<2.0,>=1.0,>=2.1 (from freezegun==0.1.18->-r measurement_collector/downloaders/ea_rivers_and_sea_levels/requirements.txt (line 3))
```

The full output is here:
https://travis-ci.org/sealevelresearch/tide-gauge-measurement-collector/jobs/49623921#L122

Curiously if I just do `pip install 'python-dateutil<2.0,>=1.0,>=2.1'` on my machine it successfully installs python-dateutil 2.4.0 (Python 3.2.3, pip 1.5.6). Is this a problem with a newer python / pip?

Is the dependency specification `'python-dateutil<2.0,>=1.0,>=2.1'` AND or OR? I don't really know what's happening here :)

**Comment by spulec** [comment]
Sorry about that. It was a bug in an old version of freezegun. You should be able to fix by using a newer freezegun.

**Comment by paulfurley** [comment]
Ah OK - thanks @spulec. Apparently my dependency updating isn't working as planned ;)
