### ISSUE TITLE
Include wheels on the PyPI release

### ISSUE THREAD

**Issue by prophile** [spulec/freezegun#84]
It would be very pleasant if the PyPI release could include a wheel as well as the source distribution, which would make `pip install freezegun` a little faster.

**Comment by spulec** [comment]
I have just pushed out version `0.3.0` to PyPI with Wheels. Thanks for the push!

**Comment by prophile** [comment]
You are a gentleman and a scholar. Any chance of a universal or Python 3 wheel?

**Comment by spulec** [comment]
Universal wheel created for `0.3.1` (I think). Let me know if it doesn't look right.

**Comment by prophile** [comment]
Works fine under Python 2.7 and Python 3.4. Thanks.

**Comment by spulec** [comment]
Awesome
