### ISSUE TITLE
Freezegun doesn't work after calling other frozen methods

### ISSUE THREAD

**Issue by jpulec** [spulec/freezegun#93]
When decorating a class with a frozen time, if a method calls out to another method on the class, it will cause the patcher to stop and undo the frozen time for the rest of the initial calling method. This appears to only happen when ```from datetime import datetime``` is called as opposed to ```import datetime```.

For example:

```python
from datetime import datetime
from freezegun import freeze_time
import unittest


@freeze_time('1980-01-01')
class FooTest(object):
    def test_bar(self):
        datetime.now() # returns 1980-01-01 00:00:00
        self.other_func() 
        datetime.now() # returns 2015-04-21 07:03:00

    def other_func(self):
        # do stuff
```

**Comment by spulec** [comment]
Thanks for opening.

Can you try the master branch and see if the commit I just pushed fixes the issue?

**Comment by jpulec** [comment]
That looks to have done it. Thanks so much!

**Comment by spulec** [comment]
Great. Heads up that I just pushed out freezegun `0.3.3` with the fix.
