### ISSUE TITLE
six.moves (again?)

### ISSUE THREAD

**Issue by craigcitro** [spulec/freezegun#95]
i ran into an issue with `six.moves` and `freezegun`, which may or may not have been due to bad versions. in particular, though, the fix in my case was to pass `ignore=['six.moves']` to `freezegun.freeze_time` -- note the lack of trailing `.` from the default ignore in the library.

any reason why you only ignore `six.moves.*` and not `six.moves` itself?

**Comment by spulec** [comment]
Thanks for opening. You are correct. Should be fixed now.

**Comment by craigcitro** [comment]
awesome, thanks @spulec!
