### ISSUE TITLE
Fakedatetime.date returns a native date object

### ISSUE THREAD

**Issue by eternicode** [spulec/freezegun#97]
As title says, it appears the FakeDatetime.date method ([see the docs](https://docs.python.org/2/library/datetime.html#datetime.datetime.date)) is not implemented, and so inherits from the native date object.  This leads to errors like `TypeError: can't compare FakeDatetime to datetime.date`.

Testcase:

```python
from unittest import TestCase
from datetime import datetime

@freeze_time(date(2015, 5, 1))
class TestDatetimeDateMethod(TestCase):
  def test_method(self):
    now = datetime.now()
    print repr(now)
    print repr(now.date())
```

Expected output:
```
FakeDatetime(2015, 5, 1, 0, 0)
FakeDate(2015, 5, 1)
```

Actual ouput:
```
FakeDatetime(2015, 5, 1, 0, 0)
datetime.date(2015, 5, 1)
```

**Comment by spulec** [comment]
Thanks for opening!

Can you test now with the latest commit on `master`? I think it is solved.

**Comment by eternicode** [comment]
Works for me! :+1:

**Comment by NickPresta** [comment]
@spulec is it likely for this fix to make it into a tagged release in the near future?

**Comment by spulec** [comment]
I just pushed out `0.3.4` for anyone that does need this fix.
